//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.TestProject.UsrMgmt.UI.Desktop.Services.Booking {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomClashFault", Namespace="http://schemas.datacontract.org/2004/07/Arvato.TestProject.UsrMgmt.Services.Contr" +
        "acts.DataContract")]
    [System.SerializableAttribute()]
    public partial class RoomClashFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Arvato.TestProject.UsrMgmt.Entity.Model.Booking[] ClashesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Arvato.TestProject.UsrMgmt.Entity.Model.Booking[] Clashes {
            get {
                return this.ClashesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClashesField, value) != true)) {
                    this.ClashesField = value;
                    this.RaisePropertyChanged("Clashes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Booking.IBookingService")]
    public interface IBookingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetBookings", ReplyAction="http://tempuri.org/IBookingService/GetBookingsResponse")]
        Arvato.TestProject.UsrMgmt.Entity.Model.Booking[] GetBookings(System.DateTime start, System.DateTime end, int userId, int roomId, bool isCanceled);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBookingService/GetBookings", ReplyAction="http://tempuri.org/IBookingService/GetBookingsResponse")]
        System.IAsyncResult BeginGetBookings(System.DateTime start, System.DateTime end, int userId, int roomId, bool isCanceled, System.AsyncCallback callback, object asyncState);
        
        Arvato.TestProject.UsrMgmt.Entity.Model.Booking[] EndGetBookings(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/CancelBooking", ReplyAction="http://tempuri.org/IBookingService/CancelBookingResponse")]
        bool CancelBooking(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBookingService/CancelBooking", ReplyAction="http://tempuri.org/IBookingService/CancelBookingResponse")]
        System.IAsyncResult BeginCancelBooking(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking, System.AsyncCallback callback, object asyncState);
        
        bool EndCancelBooking(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/SaveBooking", ReplyAction="http://tempuri.org/IBookingService/SaveBookingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Arvato.TestProject.UsrMgmt.UI.Desktop.Services.Booking.RoomClashFault), Action="http://tempuri.org/IBookingService/SaveBookingRoomClashFaultFault", Name="RoomClashFault", Namespace="http://schemas.datacontract.org/2004/07/Arvato.TestProject.UsrMgmt.Services.Contr" +
            "acts.DataContract")]
        Arvato.TestProject.UsrMgmt.Entity.Model.Booking SaveBooking(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBookingService/SaveBooking", ReplyAction="http://tempuri.org/IBookingService/SaveBookingResponse")]
        System.IAsyncResult BeginSaveBooking(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking, System.AsyncCallback callback, object asyncState);
        
        Arvato.TestProject.UsrMgmt.Entity.Model.Booking EndSaveBooking(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/CheckRoomAvailability", ReplyAction="http://tempuri.org/IBookingService/CheckRoomAvailabilityResponse")]
        Arvato.TestProject.UsrMgmt.Entity.Model.Booking[] CheckRoomAvailability(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBookingService/CheckRoomAvailability", ReplyAction="http://tempuri.org/IBookingService/CheckRoomAvailabilityResponse")]
        System.IAsyncResult BeginCheckRoomAvailability(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking, System.AsyncCallback callback, object asyncState);
        
        Arvato.TestProject.UsrMgmt.Entity.Model.Booking[] EndCheckRoomAvailability(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/CheckAssetAvailability", ReplyAction="http://tempuri.org/IBookingService/CheckAssetAvailabilityResponse")]
        Arvato.TestProject.UsrMgmt.Entity.Model.AssetBooking[] CheckAssetAvailability(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBookingService/CheckAssetAvailability", ReplyAction="http://tempuri.org/IBookingService/CheckAssetAvailabilityResponse")]
        System.IAsyncResult BeginCheckAssetAvailability(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking, System.AsyncCallback callback, object asyncState);
        
        Arvato.TestProject.UsrMgmt.Entity.Model.AssetBooking[] EndCheckAssetAvailability(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookingServiceChannel : Arvato.TestProject.UsrMgmt.UI.Desktop.Services.Booking.IBookingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBookingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBookingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Arvato.TestProject.UsrMgmt.Entity.Model.Booking[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Arvato.TestProject.UsrMgmt.Entity.Model.Booking[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CancelBookingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CancelBookingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveBookingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveBookingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Arvato.TestProject.UsrMgmt.Entity.Model.Booking Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Arvato.TestProject.UsrMgmt.Entity.Model.Booking)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckRoomAvailabilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CheckRoomAvailabilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Arvato.TestProject.UsrMgmt.Entity.Model.Booking[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Arvato.TestProject.UsrMgmt.Entity.Model.Booking[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckAssetAvailabilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CheckAssetAvailabilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Arvato.TestProject.UsrMgmt.Entity.Model.AssetBooking[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Arvato.TestProject.UsrMgmt.Entity.Model.AssetBooking[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingServiceClient : System.ServiceModel.ClientBase<Arvato.TestProject.UsrMgmt.UI.Desktop.Services.Booking.IBookingService>, Arvato.TestProject.UsrMgmt.UI.Desktop.Services.Booking.IBookingService {
        
        private BeginOperationDelegate onBeginGetBookingsDelegate;
        
        private EndOperationDelegate onEndGetBookingsDelegate;
        
        private System.Threading.SendOrPostCallback onGetBookingsCompletedDelegate;
        
        private BeginOperationDelegate onBeginCancelBookingDelegate;
        
        private EndOperationDelegate onEndCancelBookingDelegate;
        
        private System.Threading.SendOrPostCallback onCancelBookingCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveBookingDelegate;
        
        private EndOperationDelegate onEndSaveBookingDelegate;
        
        private System.Threading.SendOrPostCallback onSaveBookingCompletedDelegate;
        
        private BeginOperationDelegate onBeginCheckRoomAvailabilityDelegate;
        
        private EndOperationDelegate onEndCheckRoomAvailabilityDelegate;
        
        private System.Threading.SendOrPostCallback onCheckRoomAvailabilityCompletedDelegate;
        
        private BeginOperationDelegate onBeginCheckAssetAvailabilityDelegate;
        
        private EndOperationDelegate onEndCheckAssetAvailabilityDelegate;
        
        private System.Threading.SendOrPostCallback onCheckAssetAvailabilityCompletedDelegate;
        
        public BookingServiceClient() {
        }
        
        public BookingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetBookingsCompletedEventArgs> GetBookingsCompleted;
        
        public event System.EventHandler<CancelBookingCompletedEventArgs> CancelBookingCompleted;
        
        public event System.EventHandler<SaveBookingCompletedEventArgs> SaveBookingCompleted;
        
        public event System.EventHandler<CheckRoomAvailabilityCompletedEventArgs> CheckRoomAvailabilityCompleted;
        
        public event System.EventHandler<CheckAssetAvailabilityCompletedEventArgs> CheckAssetAvailabilityCompleted;
        
        public Arvato.TestProject.UsrMgmt.Entity.Model.Booking[] GetBookings(System.DateTime start, System.DateTime end, int userId, int roomId, bool isCanceled) {
            return base.Channel.GetBookings(start, end, userId, roomId, isCanceled);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetBookings(System.DateTime start, System.DateTime end, int userId, int roomId, bool isCanceled, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBookings(start, end, userId, roomId, isCanceled, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Arvato.TestProject.UsrMgmt.Entity.Model.Booking[] EndGetBookings(System.IAsyncResult result) {
            return base.Channel.EndGetBookings(result);
        }
        
        private System.IAsyncResult OnBeginGetBookings(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.DateTime start = ((System.DateTime)(inValues[0]));
            System.DateTime end = ((System.DateTime)(inValues[1]));
            int userId = ((int)(inValues[2]));
            int roomId = ((int)(inValues[3]));
            bool isCanceled = ((bool)(inValues[4]));
            return this.BeginGetBookings(start, end, userId, roomId, isCanceled, callback, asyncState);
        }
        
        private object[] OnEndGetBookings(System.IAsyncResult result) {
            Arvato.TestProject.UsrMgmt.Entity.Model.Booking[] retVal = this.EndGetBookings(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBookingsCompleted(object state) {
            if ((this.GetBookingsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBookingsCompleted(this, new GetBookingsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBookingsAsync(System.DateTime start, System.DateTime end, int userId, int roomId, bool isCanceled) {
            this.GetBookingsAsync(start, end, userId, roomId, isCanceled, null);
        }
        
        public void GetBookingsAsync(System.DateTime start, System.DateTime end, int userId, int roomId, bool isCanceled, object userState) {
            if ((this.onBeginGetBookingsDelegate == null)) {
                this.onBeginGetBookingsDelegate = new BeginOperationDelegate(this.OnBeginGetBookings);
            }
            if ((this.onEndGetBookingsDelegate == null)) {
                this.onEndGetBookingsDelegate = new EndOperationDelegate(this.OnEndGetBookings);
            }
            if ((this.onGetBookingsCompletedDelegate == null)) {
                this.onGetBookingsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBookingsCompleted);
            }
            base.InvokeAsync(this.onBeginGetBookingsDelegate, new object[] {
                        start,
                        end,
                        userId,
                        roomId,
                        isCanceled}, this.onEndGetBookingsDelegate, this.onGetBookingsCompletedDelegate, userState);
        }
        
        public bool CancelBooking(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking) {
            return base.Channel.CancelBooking(booking);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCancelBooking(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCancelBooking(booking, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndCancelBooking(System.IAsyncResult result) {
            return base.Channel.EndCancelBooking(result);
        }
        
        private System.IAsyncResult OnBeginCancelBooking(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking = ((Arvato.TestProject.UsrMgmt.Entity.Model.Booking)(inValues[0]));
            return this.BeginCancelBooking(booking, callback, asyncState);
        }
        
        private object[] OnEndCancelBooking(System.IAsyncResult result) {
            bool retVal = this.EndCancelBooking(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCancelBookingCompleted(object state) {
            if ((this.CancelBookingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CancelBookingCompleted(this, new CancelBookingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CancelBookingAsync(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking) {
            this.CancelBookingAsync(booking, null);
        }
        
        public void CancelBookingAsync(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking, object userState) {
            if ((this.onBeginCancelBookingDelegate == null)) {
                this.onBeginCancelBookingDelegate = new BeginOperationDelegate(this.OnBeginCancelBooking);
            }
            if ((this.onEndCancelBookingDelegate == null)) {
                this.onEndCancelBookingDelegate = new EndOperationDelegate(this.OnEndCancelBooking);
            }
            if ((this.onCancelBookingCompletedDelegate == null)) {
                this.onCancelBookingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCancelBookingCompleted);
            }
            base.InvokeAsync(this.onBeginCancelBookingDelegate, new object[] {
                        booking}, this.onEndCancelBookingDelegate, this.onCancelBookingCompletedDelegate, userState);
        }
        
        public Arvato.TestProject.UsrMgmt.Entity.Model.Booking SaveBooking(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking) {
            return base.Channel.SaveBooking(booking);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSaveBooking(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveBooking(booking, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Arvato.TestProject.UsrMgmt.Entity.Model.Booking EndSaveBooking(System.IAsyncResult result) {
            return base.Channel.EndSaveBooking(result);
        }
        
        private System.IAsyncResult OnBeginSaveBooking(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking = ((Arvato.TestProject.UsrMgmt.Entity.Model.Booking)(inValues[0]));
            return this.BeginSaveBooking(booking, callback, asyncState);
        }
        
        private object[] OnEndSaveBooking(System.IAsyncResult result) {
            Arvato.TestProject.UsrMgmt.Entity.Model.Booking retVal = this.EndSaveBooking(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveBookingCompleted(object state) {
            if ((this.SaveBookingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveBookingCompleted(this, new SaveBookingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveBookingAsync(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking) {
            this.SaveBookingAsync(booking, null);
        }
        
        public void SaveBookingAsync(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking, object userState) {
            if ((this.onBeginSaveBookingDelegate == null)) {
                this.onBeginSaveBookingDelegate = new BeginOperationDelegate(this.OnBeginSaveBooking);
            }
            if ((this.onEndSaveBookingDelegate == null)) {
                this.onEndSaveBookingDelegate = new EndOperationDelegate(this.OnEndSaveBooking);
            }
            if ((this.onSaveBookingCompletedDelegate == null)) {
                this.onSaveBookingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveBookingCompleted);
            }
            base.InvokeAsync(this.onBeginSaveBookingDelegate, new object[] {
                        booking}, this.onEndSaveBookingDelegate, this.onSaveBookingCompletedDelegate, userState);
        }
        
        public Arvato.TestProject.UsrMgmt.Entity.Model.Booking[] CheckRoomAvailability(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking) {
            return base.Channel.CheckRoomAvailability(booking);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCheckRoomAvailability(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCheckRoomAvailability(booking, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Arvato.TestProject.UsrMgmt.Entity.Model.Booking[] EndCheckRoomAvailability(System.IAsyncResult result) {
            return base.Channel.EndCheckRoomAvailability(result);
        }
        
        private System.IAsyncResult OnBeginCheckRoomAvailability(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking = ((Arvato.TestProject.UsrMgmt.Entity.Model.Booking)(inValues[0]));
            return this.BeginCheckRoomAvailability(booking, callback, asyncState);
        }
        
        private object[] OnEndCheckRoomAvailability(System.IAsyncResult result) {
            Arvato.TestProject.UsrMgmt.Entity.Model.Booking[] retVal = this.EndCheckRoomAvailability(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCheckRoomAvailabilityCompleted(object state) {
            if ((this.CheckRoomAvailabilityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CheckRoomAvailabilityCompleted(this, new CheckRoomAvailabilityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CheckRoomAvailabilityAsync(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking) {
            this.CheckRoomAvailabilityAsync(booking, null);
        }
        
        public void CheckRoomAvailabilityAsync(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking, object userState) {
            if ((this.onBeginCheckRoomAvailabilityDelegate == null)) {
                this.onBeginCheckRoomAvailabilityDelegate = new BeginOperationDelegate(this.OnBeginCheckRoomAvailability);
            }
            if ((this.onEndCheckRoomAvailabilityDelegate == null)) {
                this.onEndCheckRoomAvailabilityDelegate = new EndOperationDelegate(this.OnEndCheckRoomAvailability);
            }
            if ((this.onCheckRoomAvailabilityCompletedDelegate == null)) {
                this.onCheckRoomAvailabilityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckRoomAvailabilityCompleted);
            }
            base.InvokeAsync(this.onBeginCheckRoomAvailabilityDelegate, new object[] {
                        booking}, this.onEndCheckRoomAvailabilityDelegate, this.onCheckRoomAvailabilityCompletedDelegate, userState);
        }
        
        public Arvato.TestProject.UsrMgmt.Entity.Model.AssetBooking[] CheckAssetAvailability(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking) {
            return base.Channel.CheckAssetAvailability(booking);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCheckAssetAvailability(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCheckAssetAvailability(booking, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Arvato.TestProject.UsrMgmt.Entity.Model.AssetBooking[] EndCheckAssetAvailability(System.IAsyncResult result) {
            return base.Channel.EndCheckAssetAvailability(result);
        }
        
        private System.IAsyncResult OnBeginCheckAssetAvailability(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking = ((Arvato.TestProject.UsrMgmt.Entity.Model.Booking)(inValues[0]));
            return this.BeginCheckAssetAvailability(booking, callback, asyncState);
        }
        
        private object[] OnEndCheckAssetAvailability(System.IAsyncResult result) {
            Arvato.TestProject.UsrMgmt.Entity.Model.AssetBooking[] retVal = this.EndCheckAssetAvailability(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCheckAssetAvailabilityCompleted(object state) {
            if ((this.CheckAssetAvailabilityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CheckAssetAvailabilityCompleted(this, new CheckAssetAvailabilityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CheckAssetAvailabilityAsync(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking) {
            this.CheckAssetAvailabilityAsync(booking, null);
        }
        
        public void CheckAssetAvailabilityAsync(Arvato.TestProject.UsrMgmt.Entity.Model.Booking booking, object userState) {
            if ((this.onBeginCheckAssetAvailabilityDelegate == null)) {
                this.onBeginCheckAssetAvailabilityDelegate = new BeginOperationDelegate(this.OnBeginCheckAssetAvailability);
            }
            if ((this.onEndCheckAssetAvailabilityDelegate == null)) {
                this.onEndCheckAssetAvailabilityDelegate = new EndOperationDelegate(this.OnEndCheckAssetAvailability);
            }
            if ((this.onCheckAssetAvailabilityCompletedDelegate == null)) {
                this.onCheckAssetAvailabilityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckAssetAvailabilityCompleted);
            }
            base.InvokeAsync(this.onBeginCheckAssetAvailabilityDelegate, new object[] {
                        booking}, this.onEndCheckAssetAvailabilityDelegate, this.onCheckAssetAvailabilityCompletedDelegate, userState);
        }
    }
}
