//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.TestProject.UsrMgmt.UI.Desktop.Services.Room {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Room.IRoomService")]
    public interface IRoomService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetList", ReplyAction="http://tempuri.org/IRoomService/GetListResponse")]
        Arvato.TestProject.UsrMgmt.Entity.Model.Room[] GetList(bool enabledOnly);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/Save", ReplyAction="http://tempuri.org/IRoomService/SaveResponse")]
        Arvato.TestProject.UsrMgmt.Entity.Model.Room Save(Arvato.TestProject.UsrMgmt.Entity.Model.Room room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/Delete", ReplyAction="http://tempuri.org/IRoomService/DeleteResponse")]
        void Delete(Arvato.TestProject.UsrMgmt.Entity.Model.Room room);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomServiceChannel : Arvato.TestProject.UsrMgmt.UI.Desktop.Services.Room.IRoomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomServiceClient : System.ServiceModel.ClientBase<Arvato.TestProject.UsrMgmt.UI.Desktop.Services.Room.IRoomService>, Arvato.TestProject.UsrMgmt.UI.Desktop.Services.Room.IRoomService {
        
        public RoomServiceClient() {
        }
        
        public RoomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Arvato.TestProject.UsrMgmt.Entity.Model.Room[] GetList(bool enabledOnly) {
            return base.Channel.GetList(enabledOnly);
        }
        
        public Arvato.TestProject.UsrMgmt.Entity.Model.Room Save(Arvato.TestProject.UsrMgmt.Entity.Model.Room room) {
            return base.Channel.Save(room);
        }
        
        public void Delete(Arvato.TestProject.UsrMgmt.Entity.Model.Room room) {
            base.Channel.Delete(room);
        }
    }
}
